sudo: required
services:
  - docker

before_install:
  - docker build -t kensenh/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run kensenh/react-test npm test -- --coverage

after_success:
   - docker build -t kensenh/multi-client ./client
   - docker build -t kensenh/multi-nginx ./nginx
   - docker build -t kensenh/multi-server ./server
   - docker build -t kensenh/multi-worker ./worker
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
   - docker push kensenh/multi-client
   - docker push kensenh/multi-nginx
   - docker push kensenh/multi-server
   - docker push kensenh/multi-worker